development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: TripMap_development
  pool: 5
  username: root
  password: '123123'
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: TripMap_test
  pool: 5
  username: root
  password: '123123'
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: TripMap_production
  pool: 5
  username: root
  password: '123123'
  socket: /var/run/mysqld/mysqld.sock
